export const AUTH_COMPLETED = 'AUTH_COMPLETED'; 
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_STARTED = 'AUTH_STARTED';
export const LOGOUT_COMPLETED = 'LOGOUT_COMPLETED'; 
export const LOGOUT_FAILED = 'LOGOUT_FAILED';
export const LOGOUT_STARTED = 'LOGOUT_STARTED';