export const PLAYLIST_LIKED = 'PLAYLIST_LIKED';
export const PLAYLIST_SHARED = 'PLAYLIST_SHARED';
export const PLAYLIST_SONG_ADDED = 'PLAYLIST_SONG_ADDED';
export const PLAYLIST_SONG_REMOVED = 'PLAYLIST_SONG_REMOVED';
export const PLAYLIST_FETCH_STARTED = 'PLAYLIST_FETCH_STARTED';
export const PLAYLIST_FETCH_COMPLETED = 'PLAYLIST_FETCH_COMPLETED';
export const PLAYLIST_FETCH_FAILED = 'PLAYLIST_FETCH_FAILED'
export const PLAYLIST_SELECTED = 'PLAYLIST_SELECTED';